name: Amazon Deals Bot

permissions:
  contents: write

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */2 * * *"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}

        run: python main.py
        - name: Commit updated posts.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add posts.json

          git diff --cached --quiet || git commit -m "Update posted products"

          git push
